In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import joblib

In [2]:
legitimate_urls = pd.read_csv(r"C:\Users\VAISHNAVI\Documents\Internships\Cyber Security\20-8\data.csv")
legitimate_urls

Protocol                           Domain                         Path  \
0        http         www.liquidgeneration.com                            /   
1        http              www.onlineanime.org                            /   
2        http              www.ceres.dti.ne.jp  /~nekoi/senno/senfirst.html   
3        http                   www.galeon.com                        /kmh/   
4        http              www.fanworkrecs.com                            /   
...       ...                              ...                          ...   
1012     http                  www.penguins.cl                            /   
1013     http                www.falklands.net                            /   
1014     http          englishnf.pinguins.info                            /   
1015     http                 www.gdargaud.net    /antarctica/penguins.html   
1016     http  www.adelie.pwp.blueyonder.co.uk                            /   

      Having_IP  URL_Length  Having_@_symbol  Redirection_//_symbol  \
0             0           0                0                      0   
1             0           0                0                      0   
2             0           0                0                      0   
3             0           0                0                      0   
4             0           0                0                      0   
...         ...         ...              ...                    ...   
1012          0           0                0                      0   
1013          0           0                0                      0   
1014          0           0                0                      0   
1015          0           0                0                      0   
1016          0           0                0                      0   

      Prefix_suffix_separation  Sub_domains  tiny_url  web_traffic  \
0                            0            0         0            2   
1                            0            0         0            1   
2                            0            1         0            0   
3                            0            0         0            2   
4                            0            0         0            2   
...                        ...          ...       ...          ...   
1012                         0            0         0            2   
1013                         0            0         0            1   
1014                         0            0         0            1   
1015                         0            2         0            2   
1016                         0            1         0            1   

      domain_registration_length  dns_record  statistical_report  age_domain  \
0                              1           1                   0           1   
1                              1           1                   1           1   
2                              1           1                   0           1   
3                              1           1                   0           1   
4                              1           1                   0           1   
...                          ...         ...                 ...         ...   
1012                           1           1                   0           1   
1013                           1           1                   0           1   
1014                           1           1                   1           1   
1015                           1           1                   0           1   
1016                           1           1                   0           1   

      http_tokens  label  
0               0      0  
1               0      0  
2               0      0  
3               0      0  
4               0      0  
...           ...    ...  
1012            0      0  
1013            0      0  
1014            0      0  
1015            0      0  
1016            0      0  

[1017 rows x 17 columns]

In [3]:
phishing_urls=pd.read_csv(r"C:\Users\VAISHNAVI\Documents\Internships\Cyber Security\20-8\phishurl.csv")
phishing_urls

Protocol                                 Domain  \
0       http                     asesoresvelfit.com   
1       http  caixa.com.br.fgtsagendesaqueconta.com   
2       http                      hissoulreason.com   
3       http              unauthorizd.newebpage.com   
4       http                         133.130.103.10   
..       ...                                    ...   
993      NaN                                    NaN   
994      NaN                                    NaN   
995      NaN                                    NaN   
996      NaN                                    NaN   
997      NaN                                    NaN   

                               Path  Having_IP  URL_Length  Having_@_symbol  \
0            /media/datacredito.co/        0.0         0.0              0.0   
1    /consulta8523211/principal.php        0.0         1.0              0.0   
2                /js/homepage/home/        0.0         0.0              0.0   
3                   /webapps/66fbf/        0.0         0.0              0.0   
4                              /23/        1.0         0.0              0.0   
..                              ...        ...         ...              ...   
993                             NaN        NaN         NaN              NaN   
994                             NaN        NaN         NaN              NaN   
995                             NaN        NaN         NaN              NaN   
996                             NaN        NaN         NaN              NaN   
997                             NaN        NaN         NaN              NaN   

     Redirection_//_symbol  Prefix_suffix_separation  Sub_domains  tiny_url  \
0                      0.0                       0.0          0.0       1.0   
1                      0.0                       0.0          1.0       0.0   
2                      0.0                       0.0          0.0       0.0   
3                      0.0                       0.0          0.0       0.0   
4                      0.0                       0.0          2.0       0.0   
..                     ...                       ...          ...       ...   
993                    NaN                       NaN          NaN       NaN   
994                    NaN                       NaN          NaN       NaN   
995                    NaN                       NaN          NaN       NaN   
996                    NaN                       NaN          NaN       NaN   
997                    NaN                       NaN          NaN       NaN   

     web_traffic  domain_registration_length  dns_record  statistical_report  \
0            1.0                         1.0         1.0                 0.0   
1            1.0                         1.0         1.0                 1.0   
2            1.0                         1.0         1.0                 1.0   
3            1.0                         1.0         1.0                 1.0   
4            1.0                         1.0         1.0                 0.0   
..           ...                         ...         ...                 ...   
993          NaN                         NaN         NaN                 NaN   
994          NaN                         NaN         NaN                 NaN   
995          NaN                         NaN         NaN                 NaN   
996          NaN                         NaN         NaN                 NaN   
997          NaN                         NaN         NaN                 NaN   

     age_domain  http_tokens  label  
0           1.0          0.0      1  
1           1.0          0.0      1  
2           1.0          0.0      1  
3           1.0          0.0      1  
4           1.0          0.0      1  
..          ...          ...    ...  
993         NaN          NaN      1  
994         NaN          NaN      1  
995         NaN          NaN      1  
996         NaN          NaN      1  
997         NaN          NaN      1  

[998 rows x 17 columns]

In [4]:
urls = legitimate_urls.append(phishing_urls)

In [5]:
urls.to_csv("allurls.csv",index=False,encoding='UTF-8')

In [6]:
from sklearn.utils import shuffle
urls = shuffle(urls)
urls

Protocol                                             Domain  \
676     http                                        www.uvm.edu   
393     http                                dooglinn.beget.tech   
533      NaN                                                NaN   
976     http                                    www.netpets.com   
565     http                         www.silkenrosepersians.com   
..       ...                                                ...   
80      http                                  www.geocities.com   
964      NaN                                                NaN   
778     http                                        www.uvm.edu   
44     https  signin-activitysupport.helpcenter-supportfraud...   
742      NaN                                                NaN   

                                                Path  Having_IP  URL_Length  \
676                                        /~energy/        0.0         0.0   
393                                   /pp1/web17asp/        0.0         0.0   
533                                              NaN        NaN         NaN   
976  /birds/reference/lafeber/8/incredible_beak.html        0.0         2.0   
565                                              NaN        0.0         0.0   
..                                               ...        ...         ...   
80                       /can_it_be_sin/index_2.html        0.0         0.0   
964                                              NaN        NaN         NaN   
778                                         /~career        0.0         0.0   
44                                 /mpp/signin/f341/        0.0         1.0   
742                                              NaN        NaN         NaN   

     Having_@_symbol  Redirection_//_symbol  Prefix_suffix_separation  \
676              0.0                    0.0                       0.0   
393              0.0                    0.0                       0.0   
533              NaN                    NaN                       NaN   
976              0.0                    0.0                       0.0   
565              0.0                    0.0                       0.0   
..               ...                    ...                       ...   
80               0.0                    0.0                       0.0   
964              NaN                    NaN                       NaN   
778              0.0                    0.0                       0.0   
44               0.0                    0.0                       1.0   
742              NaN                    NaN                       NaN   

     Sub_domains  tiny_url  web_traffic  domain_registration_length  \
676          0.0       0.0          0.0                         1.0   
393          0.0       0.0          0.0                         1.0   
533          NaN       NaN          NaN                         NaN   
976          2.0       0.0          2.0                         1.0   
565          0.0       0.0          1.0                         1.0   
..           ...       ...          ...                         ...   
80           2.0       0.0          0.0                         1.0   
964          NaN       NaN          NaN                         NaN   
778          0.0       0.0          0.0                         1.0   
44           0.0       0.0          1.0                         1.0   
742          NaN       NaN          NaN                         NaN   

     dns_record  statistical_report  age_domain  http_tokens  label  
676         1.0                 0.0         1.0          0.0      0  
393         1.0                 0.0         1.0          0.0      1  
533         NaN                 NaN         NaN          NaN      1  
976         1.0                 0.0         1.0          0.0      0  
565         1.0                 1.0         1.0          0.0      0  
..          ...                 ...         ...          ...    ...  
80          1.0               

In [7]:
urls = urls.dropna()
pd.set_option('display.max_rows', None)
urls

Protocol                                             Domain  \
676      http                                        www.uvm.edu   
393      http                                dooglinn.beget.tech   
976      http                                    www.netpets.com   
309      http                                  www.podiums.co.uk   
257      http                                      marcof.pro.br   
838      http                                   en.wikipedia.org   
79       http                                sandralucashyde.org   
94       http                               www.privateholes.com   
397      http                          www.successpromotions.com   
567      http                                  www.geocities.com   
289      http                                 www.swerdlow.co.uk   
97       http                                   www.applicot.com   
264      http                             www.bsgodenderleeuw.be   
984      http                                  www.avesphoto.com   
698      http                                     debate.uvm.edu   
940      http                             www.stanfordalumni.org   
653      http                            www.unitedacademics.org   
388      http                             www.searchanalysts.com   
290      http                      checkpoint-erorr-fb005.esy.es   
361      http         adadaadjaldkadlhadlsajlshsaah.blogspot.com   
352      http                                   www.rankhigh.biz   
136      http                                 members.tripod.com   
883      http                              www.kenyabirds.org.uk   
978      http                               hatchedtoflyfree.org   
415      http                            cover-acct789345.esy.es   
308      http                                  www.pageviews.com   
91       http                                  www.angelfire.com   
970      http                                 www.birdguides.com   
166      http                                        abuv.com.br   
441      http                            www.hoursandminutes.com   
982      http                      papagaio2000.sites.uol.com.br   
120      http                                        us.imdb.com   
50       http                                        tinyurl.com   
1003     http                                   bioweb.uwlax.edu   
188      http                                         dh16.co.vu   
220      http                                 members.tripod.com   
423      http                                    www.vaxtech.com   
418      http                                hotshift.tripod.com   
139      http                                freberg.westnet.com   
117      http                                        www.awn.com   
508      http                                  www.bedoroses.com   
648      http                                        www.uvm.edu   
246      http                                 www.thincgrafx.com   
694      http                                        www.uvm.edu   
428      http                                   ring-my-bell.com   
954      http                                 www.npwrc.usgs.gov   
199      http                             stikliniekadarbnica.lv   
772      http                                        ctl.uvm.edu   
76       http                                    www.gongaga.com   
235      http                                      www.neymo.org   
68       http                                      m.webring.com   
1004     http                              www.kenyabirds.org.uk   
144      http                                        zemindar.lt   
224      http                                 www.audiolinks.com   
498      http                                www.cancellieri.org   
109      http               paialowereasterncherokeenationsc.com   
462      http                                    www.elprime.com   
998      http                                   www.birdlife.

In [8]:

urls.columns

Index(['Protocol', 'Domain', 'Path', 'Having_IP', 'URL_Length',
       'Having_@_symbol', 'Redirection_//_symbol', 'Prefix_suffix_separation',
       'Sub_domains', 'tiny_url', 'web_traffic', 'domain_registration_length',
       'dns_record', 'statistical_report', 'age_domain', 'http_tokens',
       'label'],
      dtype='object')

In [9]:
urls = urls.drop(urls.columns[[0,1,2]],axis=1)
col = ['Having_IP', 'URL_Length', 'Having_@_symbol', 'Redirection_//_symbol',
       'Prefix_suffix_separation', 'Sub_domains', 'tiny_url', 'web_traffic',
       'domain_registration_length', 'dns_record', 'statistical_report',
       'age_domain', 'http_tokens', 'label']
urls[col] = urls[col].astype(int)
urls

Having_IP  URL_Length  Having_@_symbol  Redirection_//_symbol  \
676           0           0                0                      0   
393           0           0                0                      0   
976           0           2                0                      0   
309           0           0                0                      0   
257           0           1                0                      0   
838           0           0                0                      0   
79            0           1                0                      0   
94            0           2                0                      0   
397           0           0                0                      0   
567           0           0                0                      0   
289           0           0                0                      0   
97            0           0                0                      0   
264           0           0                0                      0   
984           0           2                0                      0   
698           0           0                0                      0   
940           0           1                0                      0   
653           0           0                0                      0   
388           0           0                0                      0   
290           0           2                0                      0   
361           0           0                0                      0   
352           0           0                0                      0   
136           0           0                0                      0   
883           0           0                0                      0   
978           0           0                0                      0   
415           0           0                0                      0   
308           0           0                0                      0   
91            0           0                0                      0   
970           0           2                0                      0   
166           0           1                0                      0   
441           0           0                0                      0   
982           0           0                0                      0   
120           0           0                0                      0   
50            0           0                0                      0   
1003          0           0                0                      0   
188           0           2                0                      1   
220           0           0                0                      0   
423           0           0                0                      0   
418           0           0                0                      0   
139           0           0                0                      0   
117           0           2                0                      0   
508           0           0                0                      0   
648           0           0                0                      0   
246           0           0                0                      0   
694           0           0                0                      0   
428           0           0                0                      0   
954           0           2                0                      0   
199           0           2                0                      0   
772           0           0                0                      0   
76            0           0                0                      0   
235           0           0                0                      0   
68            0           0                0                      0   
1004          0           0                0                      0   
144           0           2                0                      0   
224           0           0                0                      0   
498           0           0                0                      0   
109           0           2   

In [10]:
urls.columns

Index(['Having_IP', 'URL_Length', 'Having_@_symbol', 'Redirection_//_symbol',
       'Prefix_suffix_separation', 'Sub_domains', 'tiny_url', 'web_traffic',
       'domain_registration_length', 'dns_record', 'statistical_report',
       'age_domain', 'http_tokens', 'label'],
      dtype='object')

In [11]:
urls_without_labels = urls.drop('label',axis=1)
urls_without_labels.columns
labels = urls['label']
urls

Having_IP  URL_Length  Having_@_symbol  Redirection_//_symbol  \
676           0           0                0                      0   
393           0           0                0                      0   
976           0           2                0                      0   
309           0           0                0                      0   
257           0           1                0                      0   
838           0           0                0                      0   
79            0           1                0                      0   
94            0           2                0                      0   
397           0           0                0                      0   
567           0           0                0                      0   
289           0           0                0                      0   
97            0           0                0                      0   
264           0           0                0                      0   
984           0           2                0                      0   
698           0           0                0                      0   
940           0           1                0                      0   
653           0           0                0                      0   
388           0           0                0                      0   
290           0           2                0                      0   
361           0           0                0                      0   
352           0           0                0                      0   
136           0           0                0                      0   
883           0           0                0                      0   
978           0           0                0                      0   
415           0           0                0                      0   
308           0           0                0                      0   
91            0           0                0                      0   
970           0           2                0                      0   
166           0           1                0                      0   
441           0           0                0                      0   
982           0           0                0                      0   
120           0           0                0                      0   
50            0           0                0                      0   
1003          0           0                0                      0   
188           0           2                0                      1   
220           0           0                0                      0   
423           0           0                0                      0   
418           0           0                0                      0   
139           0           0                0                      0   
117           0           2                0                      0   
508           0           0                0                      0   
648           0           0                0                      0   
246           0           0                0                      0   
694           0           0                0                      0   
428           0           0                0                      0   
954           0           2                0                      0   
199           0           2                0                      0   
772           0           0                0                      0   
76            0           0                0                      0   
235           0           0                0                      0   
68            0           0                0                      0   
1004          0           0                0                      0   
144           0           2                0                      0   
224           0           0                0                      0   
498           0           0                0                      0   
109           0           2   

In [12]:
from sklearn.model_selection import train_test_split
data_train, data_test, labels_train, labels_test = train_test_split(urls_without_labels, labels, test_size=0.15, random_state=10)

In [13]:
labels_train.value_counts()

0    754
1    424
Name: label, dtype: int64

In [14]:
labels_test.value_counts()

0    133
1     75
Name: label, dtype: int64

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

random_forest_classifier = RandomForestClassifier()
decision_tree_classifier = DecisionTreeClassifier()
naive_bayes_classfier = GaussianNB()
svm_classifier = SVC(kernel = 'rbf')
svm_linear_classifier = SVC(kernel = 'linear')
svm_poly_classifier = SVC(kernel = 'poly')

In [16]:
random_forest_classifier.fit(data_train,labels_train)
decision_tree_classifier.fit(data_train,labels_train)
naive_bayes_classfier.fit(data_train,labels_train)
svm_classifier.fit(data_train, labels_train)
svm_linear_classifier.fit(data_train, labels_train)
svm_poly_classifier.fit(data_train, labels_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [17]:
random_forest_prediction_label = random_forest_classifier.predict(data_test)
random_forest_prediction_label

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [18]:
decision_tree_prediction_label = decision_tree_classifier.predict(data_test)
decision_tree_prediction_label

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [19]:
naive_bayes_prediction_label = naive_bayes_classfier.predict(data_test)
naive_bayes_prediction_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
svm_prediction_label = svm_classifier.predict(data_test)
svm_prediction_label

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [21]:
svm_linear_prediction_label = svm_linear_classifier.predict(data_test)
svm_linear_prediction_label

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [22]:
svm_poly_prediction_label = svm_poly_classifier.predict(data_test)
svm_poly_prediction_label

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score
cpnfusionMatrix = confusion_matrix(labels_test,random_forest_prediction_label)
print(cpnfusionMatrix)
accuracy_score(labels_test,random_forest_prediction_label)

[[128   5]
 [ 18  57]]


0.8894230769230769

In [24]:
cpnfusionMatrix = confusion_matrix(labels_test,decision_tree_prediction_label)
print(cpnfusionMatrix)
accuracy_score(labels_test,decision_tree_prediction_label)

[[127   6]
 [ 21  54]]


0.8701923076923077

In [25]:
cpnfusionMatrix = confusion_matrix(labels_test,naive_bayes_prediction_label)
print(cpnfusionMatrix)
accuracy_score(labels_test,naive_bayes_prediction_label)

[[132   1]
 [ 71   4]]


0.6538461538461539

In [26]:
cpnfusionMatrix = confusion_matrix(labels_test,svm_prediction_label)
print(cpnfusionMatrix)
accuracy_score(labels_test,svm_prediction_label)

[[123  10]
 [ 14  61]]


0.8846153846153846

In [27]:
cpnfusionMatrix = confusion_matrix(labels_test,svm_linear_prediction_label)
print(cpnfusionMatrix)
accuracy_score(labels_test,svm_linear_prediction_label)

[[125   8]
 [ 35  40]]


0.7932692307692307

In [28]:
cpnfusionMatrix = confusion_matrix(labels_test,svm_poly_prediction_label)
print(cpnfusionMatrix)
accuracy_score(labels_test,svm_poly_prediction_label)

[[121  12]
 [ 10  65]]


0.8942307692307693

In [29]:
custom_rf_classifier = RandomForestClassifier(n_estimators = 200, n_jobs = -1,random_state =10, min_samples_leaf =4)

In [30]:
custom_rf_classifier.fit(data_train,labels_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=-1, oob_score=False, random_state=10, verbose=0,
                       warm_start=False)

In [31]:
custom_prediction_label = custom_rf_classifier.predict(data_test)

In [32]:
data_test.shape

(208, 13)

In [33]:
confusionMatrix2 = confusion_matrix(labels_test,custom_prediction_label)
print(confusionMatrix2)
accuracy_score(labels_test,custom_prediction_label)

[[128   5]
 [ 14  61]]


0.9086538461538461

## saving model


In [34]:
import joblib
filename = 'custom_rf_classifiers.sav'
joblib.dump(custom_rf_classifier, open(filename, 'wb'))

In [35]:
filename = 'custom_dtr_classifiers.sav'
joblib.dump(decision_tree_classifier, open(filename, 'wb'))

In [36]:
filename = 'custom_bayes_classifiers.sav'
joblib.dump(naive_bayes_classfier, open(filename, 'wb'))


In [37]:
filename = 'custom_svm_classifiers.sav'
joblib.dump(svm_classifier, open(filename, 'wb'))

In [38]:
filename = 'custom_svm_classifiers_linear.sav'
joblib.dump(svm_linear_classifier, open(filename, 'wb'))

In [39]:
filename = 'custom_svm_classifiers_poly.sav'
joblib.dump(svm_poly_classifier, open(filename, 'wb'))

In [40]:
loaded_model = joblib.load(open('custom_rf_classifiers.sav', 'rb'))
result = loaded_model.score(data_test,labels_test)
print(result)

0.9086538461538461


In [41]:
loaded_model = joblib.load(open('custom_dtr_classifiers.sav', 'rb'))
result = loaded_model.score(data_test,labels_test)
print(result)

0.8701923076923077


In [42]:
loaded_model = joblib.load(open('custom_svm_classifiers.sav', 'rb'))
result = loaded_model.score(data_test,labels_test)
print(result)

0.8846153846153846


In [43]:
loaded_model = joblib.load(open('custom_svm_classifiers_linear.sav', 'rb'))
result = loaded_model.score(data_test,labels_test)
print(result)

0.7932692307692307


In [44]:
loaded_model = joblib.load(open('custom_svm_classifiers_poly.sav', 'rb'))
result = loaded_model.score(data_test,labels_test)
print(result)

0.8942307692307693


In [45]:
loaded_model


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [46]:
import pandas as pd
from urllib.parse import urlparse,urlencode
import re
from bs4 import BeautifulSoup
import requests
import whois
import urllib.request
from datetime import datetime
import time
import socket
from urllib.error import HTTPError
from cython.parallel import prange

In [47]:
from datetime import datetime
itime = datetime.now()
for i in prange(0,10000):
    pass
ftime = datetime.now()
print(ftime-itime)

0:00:00.002827


In [48]:
computer_raw_data=pd.read_csv("TestingURLs.csv",header=None,names=['urls'])

In [49]:
cd = None
class FeatureExtraction:
    def __init__(self):
        pass
    
    def getProtocol(self,url):
        return urlparse(url).scheme
    
    def getDomain(self,url):
        return urlparse(url).netloc
    
    def getPath(self,url):
        return urlparse(url).path
    
    def havingIP(self,url):
      
        match=re.search('(([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\/)|' 
                    '((0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\.(0x[0-9a-fA-F]{1,2})\\/)' 
                    '(?:[a-fA-F0-9]{1,4}:){7}[a-fA-F0-9]{1,4}',url)    
        if match:
           
            return 1           
        else:
           
            return 0        
    
    def long_url(self,url):
       
        if len(url) < 54:
            return 0          
        elif len(url) >= 54 and len(url) <= 75:
            return 2         
        else:
            return 1           
    
    def have_at_symbol(self,url):
        """This function is used to check whether the URL contains @ symbol or not"""
        if "@" in url:
            return 1           
        else:
            return 0          
    
    def redirection(self,url):
        """If the url has symbol(//) after protocol then such URL is to be classified as phishing """
        if "//" in urlparse(url).path:
            return 1           
        else:
            return 0         
        
    def prefix_suffix_separation(self,url):
        
        if "-" in urlparse(url).netloc:
            return 1           
        else:
            return 0          
        
    def sub_domains(self,url):
    
        if url.count(".") < 3:
            return 0           
        elif url.count(".") == 3:
            return 2           
        else:
            return 1                 
    def shortening_service(self,url):
        match=re.search('bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|t\.co|tinyurl|tr\.im|is\.gd|cli\.gs|'
                    'yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|'
                    'short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|'
                    'doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|'
                    'db\.tt|qr\.ae|adf\.ly|goo\.gl|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|ity\.im|'
                    'q\.gs|is\.gd|po\.st|bc\.vc|twitthis\.com|u\.to|j\.mp|buzurl\.com|cutt\.us|u\.bb|yourls\.org|'
                    'x\.co|prettylinkpro\.com|scrnch\.me|filoops\.info|vzturl\.com|qr\.net|1url\.com|tweez\.me|v\.gd|tr\.im|link\.zip\.net',url)
        if match:
            return 1          
        else:
            return 0          
          
    def web_traffic(self,url):
        try:
            rank = BeautifulSoup(urllib.request.urlopen("http://data.alexa.com/data?cli=10&dat=s&url=" + url).read(), "xml").find("REACH")['RANK']
        except TypeError:
            return 1
        except HTTPError:
            return 2
        rank= int(rank)
        if (rank<100000):
            return 0
        else:
            return 2
        
    def domain_registration_length(self,url):
        dns = 0
        try:
            domain_name = whois.whois(urlparse(url).netloc)
        except:
            dns = 1
        
        if dns == 1:
            return 1    
        else:
            expiration_date = domain_name.expiration_date
            today = time.strftime('%Y-%m-%d')
            today = datetime.strptime(today, '%Y-%m-%d')
            if expiration_date is None:
                return 1
            elif type(expiration_date) is list or type(today) is list :
                return 2    
            else:
                creation_date = domain_name.creation_date
                expiration_date = domain_name.expiration_date
                if (isinstance(creation_date,str) or isinstance(expiration_date,str)):
                    try:
                        creation_date = datetime.strptime(creation_date,'%Y-%m-%d')
                        expiration_date = datetime.strptime(expiration_date,"%Y-%m-%d")
                    except:
                        return 2
                registration_length = abs((expiration_date - today).days)
                if registration_length / 365 <= 1:
                    return 1
                else:
                    return 0 
            
    def age_domain(self,url):
        dns = 0
        try:
            domain_name = whois.whois(urlparse(url).netloc)
        except:
            dns = 1
        
        if dns == 1:
            return 1
        else:
            creation_date = domain_name.creation_date
            expiration_date = domain_name.expiration_date
            if (isinstance(creation_date,str) or isinstance(expiration_date,str)):
                try:
                    creation_date = datetime.strptime(creation_date,'%Y-%m-%d')
                    expiration_date = datetime.strptime(expiration_date,"%Y-%m-%d")
                except:
                    return 2
            if ((expiration_date is None) or (creation_date is None)):
                return 1
            elif ((type(expiration_date) is list) or (type(creation_date) is list)):
                return 2
            else:
                ageofdomain = abs((expiration_date - creation_date).days)
                if ((ageofdomain/30) < 6):
                    return 1
                else:
                    return 0
     
    
    def dns_record(self,url):
        dns = 0
        try:
            domain_name = whois.whois(urlparse(url).netloc)
           
        except:
            dns = 1
        
        if dns == 1:
            return 1
        else:
            return 0
        
   
    def statistical_report(self,url):
        hostname = url
        h = [(x.start(0), x.end(0)) for x in re.finditer('https://|http://|www.|https://www.|http://www.', hostname)]
        z = int(len(h))
        if z != 0:
            y = h[0][1]
            hostname = hostname[y:]
            h = [(x.start(0), x.end(0)) for x in re.finditer('/', hostname)]
            z = int(len(h))
            if z != 0:
                hostname = hostname[:h[0][0]]
        url_match=re.search('at\.ua|usa\.cc|baltazarpresentes\.com\.br|pe\.hu|esy\.es|hol\.es|sweddy\.com|myjino\.ru|96\.lt|ow\.ly',url)
        try:
            ip_address = socket.gethostbyname(hostname)
            ip_match=re.search('146\.112\.61\.108|213\.174\.157\.151|121\.50\.168\.88|192\.185\.217\.116|78\.46\.211\.158|181\.174\.165\.13|46\.242\.145\.103|121\.50\.168\.40|83\.125\.22\.219|46\.242\.145\.98|107\.151\.148\.44|107\.151\.148\.107|64\.70\.19\.203|199\.184\.144\.27|107\.151\.148\.108|107\.151\.148\.109|119\.28\.52\.61|54\.83\.43\.69|52\.69\.166\.231|216\.58\.192\.225|118\.184\.25\.86|67\.208\.74\.71|23\.253\.126\.58|104\.239\.157\.210|175\.126\.123\.219|141\.8\.224\.221|10\.10\.10\.10|43\.229\.108\.32|103\.232\.215\.140|69\.172\.201\.153|216\.218\.185\.162|54\.225\.104\.146|103\.243\.24\.98|199\.59\.243\.120|31\.170\.160\.61|213\.19\.128\.77|62\.113\.226\.131|208\.100\.26\.234|195\.16\.127\.102|195\.16\.127\.157|34\.196\.13\.28|103\.224\.212\.222|172\.217\.4\.225|54\.72\.9\.51|192\.64\.147\.141|198\.200\.56\.183|23\.253\.164\.103|52\.48\.191\.26|52\.214\.197\.72|87\.98\.255\.18|209\.99\.17\.27|216\.38\.62\.18|104\.130\.124\.96|47\.89\.58\.141|78\.46\.211\.158|54\.86\.225\.156|54\.82\.156\.19|37\.157\.192\.102|204\.11\.56\.48|110\.34\.231\.42',ip_address)  
        except:
            return 1

        if url_match:
            return 1
        else:
            return 0
        
    def https_token(self,url):
        match=re.search('https://|http://',url)
        try:
            if match.start(0)==0 and match.start(0) is not None:
                url=url[match.end(0):]
                match=re.search('http|https',url)
                if match:
                    return 1
                else:
                    return 0
        except:
            return 1


In [50]:
protocol = []
domain = []
path = []
having_ip = []
len_url = []
having_at_symbol = []
redirection_symbol = []
prefix_suffix_separation = []
sub_domains = []
tiny_url = []
abnormal_url = []
web_traffic = []
domain_registration_length = []
dns_record = []
statistical_report = []
age_domain = []
http_tokens = []

In [51]:
fe = FeatureExtraction()
rows = len(computer_raw_data["urls"])

for i in range(0,rows):
    url=computer_raw_data["urls"][i]
    print(i ),print(url)
    protocol.append(fe.getProtocol(url))
    path.append(fe.getPath(url))
    domain.append(fe.getDomain(url))
    having_ip.append(fe.havingIP(url))
    len_url.append(fe.long_url(url))
    having_at_symbol.append(fe.have_at_symbol(url))
    redirection_symbol.append(fe.redirection(url))
    prefix_suffix_separation.append(fe.prefix_suffix_separation(url))
    sub_domains.append(fe.sub_domains(url))
    tiny_url.append(fe.shortening_service(url))
    web_traffic.append(fe.web_traffic(url))
    domain_registration_length.append(fe.domain_registration_length(url))
    dns_record.append(fe.dns_record(url))
    statistical_report.append(fe.statistical_report(url))
    age_domain.append(fe.age_domain(url))
    http_tokens.append(fe.https_token(url))

0
http://www.emuck.com:3000/archive/egan.html
1
http://danoday.com/summit.shtml
2
http://groups.yahoo.com/group/voice_actor_appreciation/links/events_and_appearanc_000985383761/
3
http://voice-international.com/
4
http://www.livinglegendsltd.com/
5
http://voicechasers.com/forum/viewforum.php?f=8
6
http://hollywoodcollectorshow.com/
7
http://www.geocities.com/hollywood/hills/8944/
8
http://asifa.proboards61.com/index.cgi?action=calendarviewall
9
http://groups.yahoo.com/group/voice_actor_appreciation/cal///group/voice_actor_appreciation/?v=42&amp;pos=
10
http://us.imdb.com/name/nm0267724/
11
http://www.pamelynferdin.com/
12
http://www.pamferdin.com/
13
http://www.monkeydog.com/
14
http://teamknightrider.com/cast/plato/plato.html
15
http://us.imdb.com/name/nm0281486/
16
http://anp.awn.com/anifest-3.html
17
http://www.awn.com/mag/issue1.7/articles/kowlaskidi1.7.html
18
http://www.awn.com/mag/issue2.7/2.7pages/2.7jacksonjones.html
19
http://www.awn.com/mag/issue1.9/articles/kowlagrinch1.9.h

In [52]:

d={'Protocol':pd.Series(protocol),'Domain':pd.Series(domain),'Path':pd.Series(path),'Having_IP':pd.Series(having_ip),
   'URL_Length':pd.Series(len_url),'Having_@_symbol':pd.Series(having_at_symbol),
   'Redirection_//_symbol':pd.Series(redirection_symbol),'Prefix_suffix_separation':pd.Series(prefix_suffix_separation),
   'Sub_domains':pd.Series(sub_domains),'tiny_url':pd.Series(tiny_url),'web_traffic' : pd.Series(web_traffic) ,
   'domain_registration_length':pd.Series(domain_registration_length),'dns_record':pd.Series(dns_record),
   'statistical_report':pd.Series(statistical_report),'age_domain':pd.Series(age_domain),'http_tokens':pd.Series(http_tokens)}
data=pd.DataFrame(d)
data

Protocol                              Domain  \
0       http                  www.emuck.com:3000   
1       http                         danoday.com   
2       http                    groups.yahoo.com   
3       http             voice-international.com   
4       http            www.livinglegendsltd.com   
5       http                    voicechasers.com   
6       http          hollywoodcollectorshow.com   
7       http                   www.geocities.com   
8       http               asifa.proboards61.com   
9       http                    groups.yahoo.com   
10      http                         us.imdb.com   
11      http               www.pamelynferdin.com   
12      http                   www.pamferdin.com   
13      http                   www.monkeydog.com   
14      http                 teamknightrider.com   
15      http                         us.imdb.com   
16      http                         anp.awn.com   
17      http                         www.awn.com   
18      http                         www.awn.com   
19      http                         www.awn.com   
20      http                         us.imdb.com   
21      http                www.voicechasers.com   
22      http                      www.vortex.com   
23      http                    starbulletin.com   
24      http                         anp.awn.com   
25      http               www.cerias.purdue.edu   
26      http                         www.awn.com   
27      http                         www.awn.com   
28      http  archives.seattletimes.nwsource.com   
29      http                   www.geocities.com   
30      http                         us.imdb.com   
31      http                www.voicechasers.com   
32      http                       patfraley.com   
33      http          nerf-herders-anonymous.net   
34      http                       www.vasta.org   
35      http                   news.toonzone.net   
36      http                  members.tripod.com   
37      http                www.radiospirits.com   
38      http                         us.imdb.com   
39      http                 freberg.westnet.com   
40      http                        www.aarp.org   
41      http                      www.cosmik.com   
42      http                      www.tsimon.com   
43      http                    www.firezine.net   
44      http                    www.thehutch.com   
45      http                   www.povonline.com   
46      http                   www.povonline.com   
47      http             www.austinchronicle.com   
48      http                  www.dawsbutler.com   
49      http                 freberg.westnet.com   
50      http                       www.rhino.com   
51      http                       hitcomedy.com   
52      http                   www.cyberonic.net   
53      http                   www.povonline.com   
54      http                 freberg.westnet.com   
55      http                    www.epinions.com   
56      http                       citypaper.net   
57      http              www.crispinfreeman.com   
58      http                   www.reelradio.com   
59      http                  www.spookytoms.com   
60      http                  www.hollowhill.com   
61      http                     www.dvdtalk.com   
62      http                         us.imdb.com   
63      http                www.voicechasers.com   
64      http                bakerstreetdozen.com   
65      http                         us.imdb.com   
66      http                   www.geocities.com   
67      http                   www.angelfire.com   
68      http                   www.geocities.com   
69      http                   www.geocities.com   
70      http              doreen.mkbmemorial.com   
71      http                   www.geocities.com   
72      http        www.behindthevoiceactors.com   
73      http              www.keyframeonline.com   
74      http                www.voicechasers.com   
75      http                         us.imdb.com   


In [53]:
data = data.dropna()
data = data.drop(data.columns[[0,1,2]],axis=1)
data

Having_IP  URL_Length  Having_@_symbol  Redirection_//_symbol  \
0            0           0                0                      0   
1            0           0                0                      0   
2            0           1                0                      0   
3            0           0                0                      0   
4            0           0                0                      0   
5            0           0                0                      0   
6            0           0                0                      0   
7            0           0                0                      0   
8            0           2                0                      0   
9            0           1                0                      1   
10           0           0                0                      0   
11           0           0                0                      0   
12           0           0                0                      0   
13           0           0                0                      0   
14           0           0                0                      0   
15           0           0                0                      0   
16           0           0                0                      0   
17           0           2                0                      0   
18           0           2                0                      0   
19           0           2                0                      0   
20           0           0                0                      0   
21           0           2                0                      0   
22           0           0                0                      0   
23           0           0                0                      0   
24           0           0                0                      0   
25           0           2                0                      0   
26           0           2                0                      0   
27           0           2                0                      0   
28           0           1                0                      0   
29           0           2                0                      0   
30           0           0                0                      0   
31           0           2                0                      0   
32           0           0                0                      0   
33           0           0                0                      0   
34           0           0                0                      0   
35           0           2                0                      0   
36           0           0                0                      0   
37           0           0                0                      0   
38           0           0                0                      0   
39           0           0                0                      0   
40           0           2                0                      0   
41           0           0                0                      0   
42           0           0                0                      0   
43           0           0                0                      0   
44           0           0                0                      0   
45           0           0                0                      0   
46           0           0                0                      0   
47           0           1                0                      0   
48           0           0                0                      0   
49           0           0                0                      0   
50           0           0                0                      0   
51           0           0                0                      0   
52           0           0                0                      0   
53           0           0                0                      0   
54           0           0                0                      0   
55           0           2                0                      0   
56           0 

In [63]:
prediction_label = svm_poly_classifier.predict(data)
prediction_label

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [55]:
val = joblib.load(open('custom_rf_classifiers.sav','rb'))

In [56]:
val


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=-1, oob_score=False, random_state=10, verbose=0,
                       warm_start=False)

In [57]:
url = "https://www.tinyurl.com/phishing"

In [58]:
protocol.append(fe.getProtocol(url))
path.append(fe.getPath(url))
domain.append(fe.getDomain(url))
having_ip.append(fe.havingIP(url))
len_url.append(fe.long_url(url))
having_at_symbol.append(fe.have_at_symbol(url))
redirection_symbol.append(fe.redirection(url))
prefix_suffix_separation.append(fe.prefix_suffix_separation(url))
sub_domains.append(fe.sub_domains(url))
tiny_url.append(fe.shortening_service(url))
web_traffic.append(fe.web_traffic(url))
domain_registration_length.append(fe.domain_registration_length(url))
dns_record.append(fe.dns_record(url))
statistical_report.append(fe.statistical_report(url))
age_domain.append(fe.age_domain(url))
http_tokens.append(fe.https_token(url))

In [59]:
d={'Protocol':pd.Series(protocol),'Domain':pd.Series(domain),'Path':pd.Series(path),'Having_IP':pd.Series(having_ip),
   'URL_Length':pd.Series(len_url),'Having_@_symbol':pd.Series(having_at_symbol),
   'Redirection_//_symbol':pd.Series(redirection_symbol),'Prefix_suffix_separation':pd.Series(prefix_suffix_separation),
   'Sub_domains':pd.Series(sub_domains),'tiny_url':pd.Series(tiny_url),'web_traffic' : pd.Series(web_traffic) ,
   'domain_registration_length':pd.Series(domain_registration_length),'dns_record':pd.Series(dns_record),
   'statistical_report':pd.Series(statistical_report),'age_domain':pd.Series(age_domain),'http_tokens':pd.Series(http_tokens)}
data=pd.DataFrame(d)
data

Protocol                              Domain  \
0       http                  www.emuck.com:3000   
1       http                         danoday.com   
2       http                    groups.yahoo.com   
3       http             voice-international.com   
4       http            www.livinglegendsltd.com   
5       http                    voicechasers.com   
6       http          hollywoodcollectorshow.com   
7       http                   www.geocities.com   
8       http               asifa.proboards61.com   
9       http                    groups.yahoo.com   
10      http                         us.imdb.com   
11      http               www.pamelynferdin.com   
12      http                   www.pamferdin.com   
13      http                   www.monkeydog.com   
14      http                 teamknightrider.com   
15      http                         us.imdb.com   
16      http                         anp.awn.com   
17      http                         www.awn.com   
18      http                         www.awn.com   
19      http                         www.awn.com   
20      http                         us.imdb.com   
21      http                www.voicechasers.com   
22      http                      www.vortex.com   
23      http                    starbulletin.com   
24      http                         anp.awn.com   
25      http               www.cerias.purdue.edu   
26      http                         www.awn.com   
27      http                         www.awn.com   
28      http  archives.seattletimes.nwsource.com   
29      http                   www.geocities.com   
30      http                         us.imdb.com   
31      http                www.voicechasers.com   
32      http                       patfraley.com   
33      http          nerf-herders-anonymous.net   
34      http                       www.vasta.org   
35      http                   news.toonzone.net   
36      http                  members.tripod.com   
37      http                www.radiospirits.com   
38      http                         us.imdb.com   
39      http                 freberg.westnet.com   
40      http                        www.aarp.org   
41      http                      www.cosmik.com   
42      http                      www.tsimon.com   
43      http                    www.firezine.net   
44      http                    www.thehutch.com   
45      http                   www.povonline.com   
46      http                   www.povonline.com   
47      http             www.austinchronicle.com   
48      http                  www.dawsbutler.com   
49      http                 freberg.westnet.com   
50      http                       www.rhino.com   
51      http                       hitcomedy.com   
52      http                   www.cyberonic.net   
53      http                   www.povonline.com   
54      http                 freberg.westnet.com   
55      http                    www.epinions.com   
56      http                       citypaper.net   
57      http              www.crispinfreeman.com   
58      http                   www.reelradio.com   
59      http                  www.spookytoms.com   
60      http                  www.hollowhill.com   
61      http                     www.dvdtalk.com   
62      http                         us.imdb.com   
63      http                www.voicechasers.com   
64      http                bakerstreetdozen.com   
65      http                         us.imdb.com   
66      http                   www.geocities.com   
67      http                   www.angelfire.com   
68      http                   www.geocities.com   
69      http                   www.geocities.com   
70      http              doreen.mkbmemorial.com   
71      http                   www.geocities.com   
72      http        www.behindthevoiceactors.com   
73      http              www.keyframeonline.com   
74      http                www.voicechasers.com   
75      http                         us.imdb.com   


In [60]:
data = data.dropna()
data = data.drop(data.columns[[0,1,2]],axis=1)
data

Having_IP  URL_Length  Having_@_symbol  Redirection_//_symbol  \
0            0           0                0                      0   
1            0           0                0                      0   
2            0           1                0                      0   
3            0           0                0                      0   
4            0           0                0                      0   
5            0           0                0                      0   
6            0           0                0                      0   
7            0           0                0                      0   
8            0           2                0                      0   
9            0           1                0                      1   
10           0           0                0                      0   
11           0           0                0                      0   
12           0           0                0                      0   
13           0           0                0                      0   
14           0           0                0                      0   
15           0           0                0                      0   
16           0           0                0                      0   
17           0           2                0                      0   
18           0           2                0                      0   
19           0           2                0                      0   
20           0           0                0                      0   
21           0           2                0                      0   
22           0           0                0                      0   
23           0           0                0                      0   
24           0           0                0                      0   
25           0           2                0                      0   
26           0           2                0                      0   
27           0           2                0                      0   
28           0           1                0                      0   
29           0           2                0                      0   
30           0           0                0                      0   
31           0           2                0                      0   
32           0           0                0                      0   
33           0           0                0                      0   
34           0           0                0                      0   
35           0           2                0                      0   
36           0           0                0                      0   
37           0           0                0                      0   
38           0           0                0                      0   
39           0           0                0                      0   
40           0           2                0                      0   
41           0           0                0                      0   
42           0           0                0                      0   
43           0           0                0                      0   
44           0           0                0                      0   
45           0           0                0                      0   
46           0           0                0                      0   
47           0           1                0                      0   
48           0           0                0                      0   
49           0           0                0                      0   
50           0           0                0                      0   
51           0           0                0                      0   
52           0           0                0                      0   
53           0           0                0                      0   
54           0           0                0                      0   
55           0           2                0                      0   
56           0 

In [61]:
data.shape

(102, 13)

In [62]:
val.predict(data)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])